### PR TITLE
HW 7 Maven support

### PR DESCRIPTION
**Pull request by adrizhinskaya**

### CODE REVIEW

**Comment by AtticSiol** [comment]
Almost correct, just few comments:
1. you moved all your files from "maven_test" root folder to "src...". Thus your structure is:
```
src
  |_ main
       |_java 
```

instead of:
```
maven_test
    |_src
        |_ main
            |_java 
```

Necessary steps:
- back name of root folder to "maven_test"
- inside it create folder src

2. add to .gitignore file instruction to ignore ".idea"  and "target" folders as well
3. add examples of how to use your collections into single main method if TicketService class

**Comment by AtticSiol** [comment]
These 2 folders have to "disappear" from git at all:
image

Try to fix it, if not - ping me, I'll try to help ;)

**Comment by adrizhinskaya** [comment]
I think, made something wrong and violated the integrity of the project. Can you please tell me what's wrong and how to fix it?
image

**Comment by adrizhinskaya** [comment]
Done!
image

**Review by AtticSiol — APPROVED** [review]

**Pull request merged**
